INSERT INTO clients(LOGIN, PASSWORD, FULL_NAME, PASSPORT, STATUS, BIRTHDAY)
VALUES ('IVAN', 'PASS','IVANOV IVAN','2343 322143','ACTIVE','1975-01-31');

INSERT INTO cards(NUMBER, ISSUER, HOLDER, OWNER_ID, STATUS, NAME)
VALUES ('2342 2342 4533 3232','Visa','IVAN IVANOV',1, 'ACTIVE','Tinkoff black');


INSERT INTO clients(LOGIN, PASSWORD, FULL_NAME, PASSPORT, STATUS, BIRTHDAY)
VALUES ('PETR', 'PASS2423','PETROV PETR','3242 867676','ACTIVE','1980-02-25');

INSERT INTO cards(NUMBER, ISSUER, HOLDER, OWNER_ID, STATUS, NAME)
VALUES ('5435 4355 3454 4354','MasterCard','PETR PETROV',2,'ACTIVE','Tinkoff black');
INSERT INTO cards(NUMBER, ISSUER, HOLDER, OWNER_ID, STATUS,NAME)
VALUES ('2222 4444 5555 3333','MIR','PETR PETROV',2,'ACTIVE', 'Tinkoff black');

INSERT INTO icons (name)
VALUES('Alfa');
INSERT INTO icons (name)
VALUES('Megafon');
INSERT INTO icons (name)
VALUES('Tinkoff');
INSERT INTO icons (name)
VALUES('Market');


INSERT INTO transactions(CARD_NAME, BILL, TRANSACTION_TYPE, CATEGORY, OWNER_ID, ICON)
VALUES ('Tinkoff black', 5000000,'Пополнение через Альфа-Банк','Пополнения',2,'Alfa');
INSERT INTO transactions(CARD_NAME, BILL, TRANSACTION_TYPE, CATEGORY, OWNER_ID, ICON)
VALUES ('Tinkoff black', -100000,'Продукты','Супермаркеты',2,'Market');
INSERT INTO transactions(CARD_NAME, BILL, TRANSACTION_TYPE, CATEGORY, OWNER_ID, ICON)
VALUES ('Tinkoff black', -100000,'Пополнение телефона','Мобильная связь',2,'Megafon');
INSERT INTO transactions(CARD_NAME, BILL, TRANSACTION_TYPE, CATEGORY, OWNER_ID, ICON)
VALUES ('Tinkoff black', -100000,'Перевод','Переводы',2,'Tinkoff');
